[package]
name = "UrlSniper"
version = "0.1.0"
edition = "2024"
authors = ["Nitish Patil"]
description = "ğŸ•µï¸â€â™‚ï¸ Terminal-based Suspicious URL Analyzer built in Rust"
license = "MIT"

[dependencies]
regex = "1"
url = "2"
colored = "2"